### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by saqie1393** [baselsayeh/e5577s_321_kernel#1]
Solved

**Comment by baselsayeh** [comment]
Hello,
Please provide more info on what you're trying to do
What are you trying to patch? on which device?

**Comment by saqie1393** [comment]
This is unlock method for any secureboot modem like E5573 E5577 E8372 Etc...But find ecall arm value ...this script author say find the value in vxwork partiation not so much guide...

**Comment by saqie1393** [comment]
![bFUwlCo.png](https://user-images.githubusercontent.com/57568565/118262948-0f214280-b4cf-11eb-83c4-492bebe487e5.png)

**Comment by baselsayeh** [comment]
@saqie1393 
The script offsets will need to be reverse engineered for each firmware (if needed)
Are you trying to build a custom firmware for e5573cs-322 or for another device?

**Comment by saqie1393** [comment]
every firmware different address ... but problem is how to find that ... already modified firmware install adb and telnet..This picture show so many firmware find the address

![Screenshot_20210514-164049_Chrome.jpg](https://user-images.githubusercontent.com/57568565/118265828-2feb9700-b4d3-11eb-8517-cebfe0196cc9.jpg)

**Comment by saqie1393** [comment]
![ida.png](https://user-images.githubusercontent.com/57568565/118266434-04b57780-b4d4-11eb-901f-14fab1c823ed.png)

This is Vxwork balong modem bin file ....but dont know how to find ...loaction that address

**Comment by saqie1393** [comment]
https://4pda.ru/forum/index.php?showtopic=582284&view=findpost&p=36977362

**Comment by baselsayeh** [comment]
@saqie1393 
on what device you need to modify its firmware exactly? and which firmware?
can you provide a copy of /proc/kallsyms and /proc/iomem

**Comment by saqie1393** [comment]
> @saqie1393 
> on what device you need to modify its firmware exactly? and which firmware?
> can you provide a copy of /proc/kallsyms and /proc/iomem
> 

ok i post

**Comment by saqie1393** [comment]
https://www.mediafire.com/file/56rcur3le3ipox5/kallsyms.txt/file

**Comment by baselsayeh** [comment]
> https://www.mediafire.com/file/56rcur3le3ipox5/kallsyms.txt/file

I need more info. Is it E8372? can you provide /proc/iomem and the kernel log (`dmesg > /tmp/kernel.log`) then copy `/tmp/kernel.log`
And on what firmware this device was on?

**Comment by baselsayeh** [comment]
> https://www.mediafire.com/file/56rcur3le3ipox5/kallsyms.txt/file

(Note: these instructions will work with current efuse firmwares, and is NOT guaranteed to work with later versions/models other than [this list](https://github.com/Huawei-LTE-routers-mods/README/blob/master/permalocked_device_unlock.md))

After disassembling vxworks, i found out that a function referencing the string "WAS_CSEL_MNTN_TreselectionTimerStopEventRpt" was checking if the device is unlocked

Search for the string "WAS_CSEL_MNTN_TreselectionTimerStopEventRpt"
![image](https://user-images.githubusercontent.com/3438985/118379115-133d8500-b5e1-11eb-8df5-6e5c87fdc4c5.png),
Go to each function that references this string (in E5573cs-322 21.333.64.00.1456, it was FUN_005d7174). One of them should check for == '\x01'
![image](https://user-images.githubusercontent.com/3438985/118379635-6107bc80-b5e4-11eb-8568-c8068c8c800d.png)

The destination pointer location (the highlighted red location) should contain the location needed for simunlock.sh

If the string "WAS_CSEL_MNTN_TreselectionTimerStopEventRpt" wasn't referenced by any function, then try "WAS_CSEL_PhyLrrcEutraMeasStopInIdleCnf", or use bindiff to find offsets compared to E5573cs-322 21.333.64.00.1456 (use function FUN_005d75f4 when comparing)

**Comment by baselsayeh** [comment]
> https://www.mediafire.com/file/56rcur3le3ipox5/kallsyms.txt/file

(Note: these instructions will work with current efuse firmwares, and is NOT guaranteed to work with later versions/models other than [this list](https://github.com/Huawei-LTE-routers-mods/README/blob/master/permalocked_device_unlock.md))

After disassembling vxworks, i found out that a function referencing the string "WAS_CSEL_MNTN_TreselectionTimerStopEventRpt" was checking if the device is unlocked

Search for the string "WAS_CSEL_MNTN_TreselectionTimerStopEventRpt"
![image](https://user-images.githubusercontent.com/3438985/118379115-133d8500-b5e1-11eb-8df5-6e5c87fdc4c5.png),
Go to each function that references this string (in E5573cs-322 21.333.64.00.1456, it was FUN_005d7174). One of them should check for == '\x01'
![image](https://user-images.githubusercontent.com/3438985/118379635-6107bc80-b5e4-11eb-8568-c8068c8c800d.png)

The destination pointer location (the highlighted red location) should contain the location needed for simunlock.sh

If the string "WAS_CSEL_MNTN_TreselectionTimerStopEventRpt" wasn't referenced by any function, then try "WAS_CSEL_PhyLrrcEutraMeasStopInIdleCnf", or use bindiff to find offsets compared to E5573cs-322 21.333.64.00.1456 (use function FUN_005d75f4 when comparing)

**Comment by saqie1393** [comment]
Vxwork just extract  with 7zip and open in ida dissambler ?
some little instruction about open and cpu start adresss
