### ISSUE TITLE
 .....

### ISSUE THREAD

**Issue by saqie1393** [baselsayeh/e5577s_321_kernel#2]
solve

**Comment by baselsayeh** [comment]
> Vxwork just extract with 7zip and open in ida dissambler ?
> some little instruction about open and cpu start adresss
> 
> Disassembly with IDA fails, as I do not know the loader address.
> 
> ![2.png](https://user-images.githubusercontent.com/57568565/118385440-38a1b180-b628-11eb-826e-63ab3a01f6ab.png)
> 
> _Originally posted by @saqie1393 in [#1 (comment)](https://github.com/baselsayeh/e5577s_321_kernel/issues/1#issuecomment-841754499)_

Should work.
Try running 'auto analysis' or anything like that in ida. And make sure to choose "armv7 little endian" as an architecture.

**Comment by saqie1393** [comment]
which dissambler you use for analyze...vxwork extract with 7zip....?

i use IDA 32BiT

![20210516_145037.jpg](https://user-images.githubusercontent.com/57568565/118393038-4a01b280-b656-11eb-9a6f-b355a4de0a8a.jpg)
![20210516_145050.jpg](https://user-images.githubusercontent.com/57568565/118393053-5d148280-b656-11eb-9871-562d0332510d.jpg)
![20210516_145114.jpg](https://user-images.githubusercontent.com/57568565/118393055-60a80980-b656-11eb-89e2-5a3cce6b6708.jpg)

this is my ida setting where are serach sting value?

**Comment by saqie1393** [comment]
![20210516_151115.jpg](https://user-images.githubusercontent.com/57568565/118393513-03618780-b659-11eb-8b7f-a366c66634af.jpg)

**Comment by baselsayeh** [comment]
> which dissambler you use for analyze...vxwork extract with 7zip....?
> 
> i use IDA 32BiT
> 
> ![20210516_145037.jpg](https://user-images.githubusercontent.com/57568565/118393038-4a01b280-b656-11eb-9a6f-b355a4de0a8a.jpg)
> ![20210516_145050.jpg](https://user-images.githubusercontent.com/57568565/118393053-5d148280-b656-11eb-9871-562d0332510d.jpg)
> ![20210516_145114.jpg](https://user-images.githubusercontent.com/57568565/118393055-60a80980-b656-11eb-89e2-5a3cce6b6708.jpg)
> 
> this is my ida setting where are serach sting value?

correct. as for the loading address, it should be located at offset 0x38 from the vxworks partition.
![image](https://user-images.githubusercontent.com/3438985/118394048-0b1a2f80-b64b-11eb-8340-58454d1ed412.png)
it should be 0x50d10000

**Comment by saqie1393** [comment]
![20210516_160046.jpg](https://user-images.githubusercontent.com/57568565/118394743-e9777300-b65f-11eb-978d-99fba190308e.jpg)

look like this setting ?

**Comment by saqie1393** [comment]
same frimware 21.333.64.00.1456 analyze but not find....this type of window

![118379115-133d8500-b5e1-11eb-8df5-6e5c87fdc4c5.png](https://user-images.githubusercontent.com/57568565/118394872-c0a3ad80-b660-11eb-9f2b-d9171d858ed3.png)

**Comment by baselsayeh** [comment]
> same frimware 21.333.64.00.1456 analyze but not find....this type of window
> 
> ![118379115-133d8500-b5e1-11eb-8df5-6e5c87fdc4c5.png](https://user-images.githubusercontent.com/57568565/118394872-c0a3ad80-b660-11eb-9f2b-d9171d858ed3.png)

Are you sure that you have done the auto-analysis?????
try going to address 0x512E7174 (loading address + function address). Do you see any code that has been disassembled?

**Comment by saqie1393** [comment]
> > same frimware 21.333.64.00.1456 analyze but not find....this type of window
> > 
> > ![118379115-133d8500-b5e1-11eb-8df5-6e5c87fdc4c5.png](https://user-images.githubusercontent.com/57568565/118394872-c0a3ad80-b660-11eb-9f2b-d9171d858ed3.png)
> 
> Are you sure that you have done the auto-analysis?????
> try going to address 0x512E7174 (loading address + function address). Do you see any code that has been disassembled?

auto analyzed is on....loading address and rom address change.....with 0x512E7174...

show this type of window

![20210516_163101.jpg](https://user-images.githubusercontent.com/57568565/118395488-1fb6f180-b664-11eb-849e-5467558a286d.jpg)

**Comment by baselsayeh** [comment]
> > > same frimware 21.333.64.00.1456 analyze but not find....this type of window
> > > ![118379115-133d8500-b5e1-11eb-8df5-6e5c87fdc4c5.png](https://user-images.githubusercontent.com/57568565/118394872-c0a3ad80-b660-11eb-9f2b-d9171d858ed3.png)
> > 
> > 
> > Are you sure that you have done the auto-analysis?????
> > try going to address 0x512E7174 (loading address + function address). Do you see any code that has been disassembled?
> 
> auto analyzed is on....loading address and rom address change.....with 0x512E7174...
> 
> show this type of window
> 
> ![20210516_163101.jpg](https://user-images.githubusercontent.com/57568565/118395488-1fb6f180-b664-11eb-849e-5467558a286d.jpg)

Are you sure that you are using the same firmware (E5573cs-322 21.333.64.00.1456)? can you send me the vxworks file?

**Comment by saqie1393** [comment]
> > > > same frimware 21.333.64.00.1456 analyze but not find....this type of window
> > > > ![118379115-133d8500-b5e1-11eb-8df5-6e5c87fdc4c5.png](https://user-images.githubusercontent.com/57568565/118394872-c0a3ad80-b660-11eb-9f2b-d9171d858ed3.png)
> > > 
> > > 
> > > Are you sure that you have done the auto-analysis?????
> > > try going to address 0x512E7174 (loading address + function address). Do you see any code that has been disassembled?
> > 
> > 
> > auto analyzed is on....loading address and rom address change.....with 0x512E7174...
> > show this type of window
> > ![20210516_163101.jpg](https://user-images.githubusercontent.com/57568565/118395488-1fb6f180-b664-11eb-849e-5467558a286d.jpg)
> 
> Are you sure that you are using the same firmware (E5573cs-322 21.333.64.00.1456)? can you send me the vxworks file?

https://www.mediafire.com/file/t49navi0wypbte3/balong_modem.7z/file

**Comment by baselsayeh** [comment]
> > > > > same frimware 21.333.64.00.1456 analyze but not find....this type of window
> > > > > ![118379115-133d8500-b5e1-11eb-8df5-6e5c87fdc4c5.png](https://user-images.githubusercontent.com/57568565/118394872-c0a3ad80-b660-11eb-9f2b-d9171d858ed3.png)
> > > > 
> > > > 
> > > > Are you sure that you have done the auto-analysis?????
> > > > try going to address 0x512E7174 (loading address + function address). Do you see any code that has been disassembled?
> > > 
> > > 
> > > auto analyzed is on....loading address and rom address change.....with 0x512E7174...
> > > show this type of window
> > > ![20210516_163101.jpg](https://user-images.githubusercontent.com/57568565/118395488-1fb6f180-b664-11eb-849e-5467558a286d.jpg)
> > 
> > 
> > Are you sure that you are using the same firmware (E5573cs-322 21.333.64.00.1456)? can you send me the vxworks file?
> 
> https://www.mediafire.com/file/t49navi0wypbte3/balong_modem.7z/file

Just noticed the picture. Go to sub_512E7174 (press g and type 0x512e7174). Does ida recognized that as a function? if so, decompile that function (f5), and you should find the script offset there.

**Comment by saqie1393** [comment]
can you share screenshot?

**Comment by baselsayeh** [comment]
> can you share screenshot?

of the disassembled function?
![image](https://user-images.githubusercontent.com/3438985/118398767-c8645180-b662-11eb-9151-199dda7e4fb3.png)
it will look slightly different, as im using ghidra rather than ida

**Comment by saqie1393** [comment]
![20210516_182459.jpg](https://user-images.githubusercontent.com/57568565/118399057-b4c1e680-b674-11eb-87a6-81683039ae1f.jpg)

show start up this one?

**Comment by baselsayeh** [comment]
> ![20210516_182459.jpg](https://user-images.githubusercontent.com/57568565/118399057-b4c1e680-b674-11eb-87a6-81683039ae1f.jpg)
> 
> show start up this one?

no. keep the loading address to 0x50d10000.
- Start a new project
- select the vxworks file
- set the architecture to armv7 a&r
- set the loading address to 0x50d10000
- start the auto analyzer
- wait for the auto analyzer to complete
- go to the address  0x512e7174 (press g and type 0x512e7174 and hit ok)
- Do you see disassembled instructions, or some random data (DCB, DCW, ...)?????

**Comment by saqie1393** [comment]
you can find in this vxwork Offset value 52612?

**Comment by baselsayeh** [comment]
> you can find in this vxwork Offset value 52612?

Yes you can.
![image](https://user-images.githubusercontent.com/3438985/118399343-69eca280-b665-11eb-9e15-08e1b1309cb9.png)

this process will be different for each firmware/device.
searching for "WAS_CSEL_MNTN_TreselectionTimerStopEventRpt" or "WAS_CSEL_PhyLrrcEutraMeasStopInIdleCnf" xrefs will lead to this offset
![image](https://user-images.githubusercontent.com/3438985/118399425-be901d80-b665-11eb-912d-7447b9b36715.png)
(The xrefs are shown on the right, the function we are interested in is FUN_512e7174)

i would recommend you to use the offsets that are already found, so that you dont have to do this reverse engineer process if you dont have any prior knowledge about

**Comment by saqie1393** [comment]
> > you can find in this vxwork Offset value 52612?
> 
> Yes you can.
> ![image](https://user-images.githubusercontent.com/3438985/118399343-69eca280-b665-11eb-9e15-08e1b1309cb9.png)
> 
> this process will be different for each firmware/device.
> searching for "WAS_CSEL_MNTN_TreselectionTimerStopEventRpt" or "WAS_CSEL_PhyLrrcEutraMeasStopInIdleCnf" xrefs will lead to this offset
> ![image](https://user-images.githubusercontent.com/3438985/118399425-be901d80-b665-11eb-912d-7447b9b36715.png)
> (The xrefs are shown on the right, the function we are interested in is FUN_512e7174)
> 
> i would recommend you to use the offsets that are already found, so that you dont have to do this reverse engineer process if you dont have any prior knowledge about

IDA pro not find this ...can this software work in window pc?

**Comment by baselsayeh** [comment]
> > > you can find in this vxwork Offset value 52612?
> > 
> > 
> > Yes you can.
> > ![image](https://user-images.githubusercontent.com/3438985/118399343-69eca280-b665-11eb-9e15-08e1b1309cb9.png)
> > this process will be different for each firmware/device.
> > searching for "WAS_CSEL_MNTN_TreselectionTimerStopEventRpt" or "WAS_CSEL_PhyLrrcEutraMeasStopInIdleCnf" xrefs will lead to this offset
> > ![image](https://user-images.githubusercontent.com/3438985/118399425-be901d80-b665-11eb-912d-7447b9b36715.png)
> > (The xrefs are shown on the right, the function we are interested in is FUN_512e7174)
> > i would recommend you to use the offsets that are already found, so that you dont have to do this reverse engineer process if you dont have any prior knowledge about
> 
> IDA pro not find this ...can this software work in window pc?

yes it can, but it will also work on ida using auto analysis.

**Comment by saqie1393** [comment]
you find on ida  i am different installation of ida pro  but not find that......?

you can find this firmware code 

https://www.mediafire.com/file/de32wvcb2vhmowa/balong_modemE5577.7z/file

**Comment by saqie1393** [comment]
i am install  ghidra how to search  WAS_CSEL_MNTN_TreselectionTimerStopEventRpt ?

**Comment by baselsayeh** [comment]
the offset is 0x5261B268, found at function 0x005dc9fc
________________________________

**Comment by baselsayeh** [comment]
Search -> for strings -> search
after the search is complete, copy and paste the string to the filter box, and you should find it in the results

________________________________

**Comment by saqie1393** [comment]
how much time take complete search this software?

**Comment by saqie1393** [comment]
> how much time take complete search this software?

search speed very slow any way to fast search

**Comment by saqie1393** [comment]
![20210516_215305.jpg](https://user-images.githubusercontent.com/57568565/118405385-1ee88480-b691-11eb-9b38-59d1fb572836.jpg)

I am not find this offset 52612EA0

**Comment by saqie1393** [comment]
https://www.mediafire.com/file/t49navi0wypbte3/balong_modem.7z/file

ecall __arm_ioremap 0x52612EA0 1  1

**Comment by baselsayeh** [comment]
> https://www.mediafire.com/file/t49navi0wypbte3/balong_modem.7z/file
> 
> ecall __arm_ioremap 0x52612EA0 1 1

In this binary, the function is in FUN_005d74f4, and the offset is 0x52612ea0
![image](https://user-images.githubusercontent.com/3438985/118408394-23f80480-b68e-11eb-9dfd-ffd7b8b8f58d.png)


If you cant find it by string search, use bindiff and compare between the (E5573cs-322 21.333.64.00.1456 vxworks) and the target vxworks image. The program will compare the binaries and find similar functions. after using it on this firmware, FUN_005d7174 (from 21.333.64.00.1456) should be identical to (FUN_005d74f4)
read the bindiff manual [here](https://www.zynamics.com/bindiff/manual/index.html)

**Comment by saqie1393** [comment]
loading address set 0x51d0000 in ghidra software ...when analyze ...this binary ..

**Comment by baselsayeh** [comment]
> loading address set 0x51d0000 in ghidra software ...when analyze ...this binary ..

For now, you dont need to set the loading address.

**Comment by saqie1393** [comment]
https://www.mediafire.com/file/jmauk4ozxq0fkpb/modem.zip/file

i have this modem i understand other firmware little bit  analyse  you can find that my modem offset  ?

**Comment by saqie1393** [comment]
B310 21.333.01.00.306

**Comment by saqie1393** [comment]
any simple way to find offset any new firmware load  search value  ? in ghidra extension ?

**Comment by baselsayeh** [comment]
> https://www.mediafire.com/file/jmauk4ozxq0fkpb/modem.zip/file
> 
> i have this modem i understand other firmware little bit analyse you can find that my modem offset ?

the value is 0x52aeb9f0, located in FUN_005de258

**Comment by baselsayeh** [comment]
> any simple way to find offset any new firmware load search value ? in ghidra extension ?

I'm afraid not. You need to have reverse engineering experience

**Comment by saqie1393** [comment]
> > any simple way to find offset any new firmware load search value ? in ghidra extension ?
> 
> I'm afraid not. You need to have reverse engineering experience

Delete this  whole topic beacuse its not issue     its chat  coversation..
