### ISSUE TITLE
.....

### ISSUE THREAD

**Issue by saqie1393** [baselsayeh/e5577s_321_kernel#4]
Solved

**Comment by baselsayeh** [comment]
Hello

always load the E5573cs-322 21.333.64.00.1456 image as the first binary.
,ake sure that the function at 0x5d7174 has been detected, and load the second firmware.
bindiff should detect similar functions, and you should be able to see the matched function from the target firmware.
________________________________
From: saqie1393 ***@***.***>
Sent: Tuesday, May 18, 2021 9:21 PM
To: baselsayeh/e5577s_321_kernel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [baselsayeh/e5577s_321_kernel] BinDiff ? (#4)


Dear
How to use bin diff after 1 bin are 21.333.64.00.1456 and second other ..

[1]<https://user-images.githubusercontent.com/57568565/118703638-c1d70500-b82f-11eb-9abe-346375dee746.png>
[2]<https://user-images.githubusercontent.com/57568565/118703654-c7cce600-b82f-11eb-921a-05b955ca1046.png>

**Comment by saqie1393** [comment]
Dear i am several try with bindiff to find E5573cs offset but not find ..E8372 already find same version firmware

https://www.mediafire.com/file/j4q8c14f5nm1a3h/balong_modem_E5573_21.328.03.00.306.7z/file

https://www.mediafire.com/file/vuiucjx2h92ezj6/balong_modem_E8372_21.328.03.00.306.7z/file
E8372 offset
0x52617A0C
