### ISSUE TITLE
How to disable signature verfication ...ida pro do this fuction? for other modem..?

### ISSUE THREAD

**Issue by saqie1393** [baselsayeh/e5577s_321_kernel#5]
How to disable signature verfication ...ida pro do this fuction? for other modem..?

_Originally posted by @saqie1393 in https://github.com/baselsayeh/e5577s_modified_source/issues/2#issuecomment-849294370_

**Comment by saqie1393** [comment]
Dear you not reply ....

**Comment by baselsayeh** [comment]
> How to disable signature verfication ...ida pro do this fuction? for other modem..?
> 
> _Originally posted by @saqie1393 in [baselsayeh/e5577s_modified_source#2 (comment)](https://github.com/baselsayeh/e5577s_modified_source/issues/2#issuecomment-849294370)_

This may depend on each firmware and device, but generally
- Patch any call to "dload_check_outside_load_safety" to return zero
- Patch the function "dload_get_auth_info" to skip any check to the variable "g_auth_info"
- Patch any call to "dload_check_inside_load_safety" to return zero

You need arm reverse engineering knowledge to patch the binaries,
but the ones i used all have debugging symbols enabled, which will make it a bit easier
